"""Init SQLite

Revision ID: 14b8e19f96a0
Revises: 
Create Date: 2026-04-22 20:09:49.371025
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '14b8e19f96a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('api_base_url', sa.String(length=255), nullable=False),
    sa.Column('schedule_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_slug'), 'sources', ['slug'], unique=True)
    op.create_table('runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_stored', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_idempotency_key'), 'runs', ['idempotency_key'], unique=False)
    op.create_index('ix_runs_source_started', 'runs', ['source_id', 'started_at'], unique=False)
    op.create_table('event_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_type_created', 'event_logs', ['event_type', 'created_at'], unique=False)
    op.create_table('freshness_status',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_id', sa.Uuid(), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('staleness_minutes', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_table('normalized_signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('signal_key', sa.String(length=100), nullable=False),
    sa.Column('signal_value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('signal_unit', sa.String(length=30), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signals_observed', 'normalized_signals', ['observed_at'], unique=False)
    op.create_index('ix_signals_source_type', 'normalized_signals', ['source_id', 'signal_type'], unique=False)
    op.create_table('quality_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('check_name', sa.String(length=100), nullable=False),
    sa.Column('check_status', sa.String(length=20), nullable=False),
    sa.Column('expected_value', sa.String(length=255), nullable=False),
    sa.Column('actual_value', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quality_source_status', 'quality_checks', ['source_id', 'check_status'], unique=False)
    op.create_table('raw_payloads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_payloads_source_fetched', 'raw_payloads', ['source_id', 'fetched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_payloads_source_fetched', table_name='raw_payloads')
    op.drop_table('raw_payloads')
    op.drop_index('ix_quality_source_status', table_name='quality_checks')
    op.drop_table('quality_checks')
    op.drop_index('ix_signals_source_type', table_name='normalized_signals')
    op.drop_index('ix_signals_observed', table_name='normalized_signals')
    op.drop_table('normalized_signals')
    op.drop_table('freshness_status')
    op.drop_index('ix_events_type_created', table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index('ix_runs_source_started', table_name='runs')
    op.drop_index(op.f('ix_runs_idempotency_key'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_sources_slug'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
